### ISSUE TITLE
Nine Aligning bug

### ISSUE THREAD

**Issue by AccelShiftx** [the-casle/nine#5]
![8c9285eb-d29e-4227-a4f2-fcd014b3e72b](https://user-images.githubusercontent.com/41006159/52519749-78d09780-2c9b-11e9-94d6-feffce43ed70.png)
![c6abc870-477d-4c43-b583-9d857c38d323](https://user-images.githubusercontent.com/41006159/52519750-79692e00-2c9b-11e9-9f28-c36d76c33289.png)
Like the screenshot above, right corner's sticker isn't in the right place.
On iphone x 11.3.1
also to the developer
I recently helped two of my friends plus me installed Nine,
but we're having random crashes.
Are there any known bugs that causes Nine to crash videosubscriptionsd?
Anyway I'll make sure if it's Nine's problem when i get the chance and get back to you

**Comment by the-casle** [comment]
By crash do you mean safemode? Also, if you are still in iOS 11 I have a deb that may fix the issue with sticker. (Haven’t tested because on 12)

**Comment by AccelShiftx** [comment]
Well I’ve updated to iOS 12 too.
Haven’t installed Nine cause in my knowledge it’s not updated for 12 yet?
(Take your time, I really love the whole design of Nine)
And about random crashes(safe mode and random resprings), I tested with uninstalling Nine from both my friend’s device and there was no more crashes since.(IOS 11.1.1 6s plus, IOS 11.2.6 7 plus)

**Comment by the-casle** [comment]
Awesome, so there’s a crash report. You can try installing cr4sher and it logs out the crashes. I tweeted out a work in progress version of nine that’s compatible with iOS 12.
